name: Moonlight
attributes:
  ORGANIZATIONNAME: Christopher Olsen
options:
  deploymentTarget:
    iOS: "13.0"
  groupSortPosition: top
  minimumXcodeGenVersion: 2.15.1

targets:
  Moonlight:
    scheme:
      testTargets:
        - ChildCareAttendanceTests
    platform: iOS
    type: application
    settings:
      base:
        DEVELOPMENT_TEAM: GDEYN6H976
        TARGETED_DEVICE_FAMILY: "1" #iPhone
        CURRENT_PROJECT_VERSION: 1
        PRODUCT_BUNDLE_IDENTIFIER: com.caolsen.Moonlight
      configs:
        Debug:
          PROVISIONING_PROFILE_SPECIFIER: "match Development com.caolsen.Moonlight"
        Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
          PROVISIONING_PROFILE_SPECIFIER: "match AppStore com.caolsen.Moonlight"
    sources: Moonlight

  ChildCareAttendanceTests:
    platform: iOS
    type: bundle.unit-test
